# GgoReleaser configuration.
builds:
- env:
  - CGO_ENABLED=0
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
nfpm:
  name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  homepage:  https://github.com/mtulio/go-url
  description: Make URL tests for each endpoint served by endpoint
  maintainer: Marco Tulio R Braga <root@mtulio.eng.br>
  license: Apache-2
  vendor: Go-url
  formats:
  - deb
  - rpm
  dependencies:
  - git
  recommends:
  - rpm

  # https://goreleaser.com/customization/#Docker
dockers:
- binary: go-url
  image: mtulio/go-url
  goos: linux
  goarch: amd64
  skip_push: false
  dockerfile: hack/Dockerfile-goreleaser
  tag_templates:
    - "{{ .Tag }}"
    - "v{{ .Major }}"
    - "v{{ .Major }}.{{ .Minor }}"
    - latest