version: '3.3'

services:
   pushgateway:
     image: prom/pushgateway
     ports:
       - "9091:9091"
     restart: always
   prometheus:
     image: prom/prometheus
     volumes:
       - ./prometheus.yml:/prometheus.yml
     ports:
       - "9090:9090"
     restart: always
     command:
      - --config.file=/prometheus.yml

