global:
  scrape_interval:     30s # default: 15s
  evaluation_interval: 30s # default: 15s
  scrape_timeout:      5s  # default: 10s

scrape_configs:
  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true

    static_configs:
      - targets:
        - 'pushgateway:9091'


